[package]
name = "devefi"
version = "0.1.0"
description = "Neutrinite DeVeFi Framework"
repository = "https://github.com/Neutrinomic/devefi"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
map = "9.0.1"
swb = "1.1.1"
stableheapbtreemap = "1.5.0"
base = "0.12.1"
serde = "3.1.0"
devefi-icp-ledger = "../devefi_icp_ledger/"
devefi-icrc-ledger = "../devefi_icrc_ledger/"
prng = "0.0.5"
account = "1.0.1"

[dev-dependencies]
itertools = "0.2.1"
