[package]
name = "devefi"
version = "0.2.8"
description = "Neutrinite DeVeFi Framework"
repository = "https://github.com/Neutrinomic/devefi"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
map = "9.0.1"
base = "0.12.1"
prng = "0.0.5"
account = "1.0.1"
itertools = "0.2.1"
devefi-icrc-ledger = "1.4.2"
devefi-icp-ledger = "1.4.2"
